version: '3'

services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - home:/home/wonky
    healthcheck:
      test: ["CMD-SHELL", "curl -f 127.0.0.1:8888/api || exit 1"]
      interval: 30s
      timeout: 60s
      retries: 3
    ports:
      - "127.0.0.1:8888:8888"

volumes:
  home:
