version: '3'

services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - home:/home/wonky
    ports:
      - "8888:8888"

volumes:
  home:
